### ISSUE TITLE
[Suggesten]Pet leveling

### ISSUE THREAD

**Issue by TerravoltPrime** [RobertSkalko/Mine-And-Slash-Rework#120]
### Tell us about your Suggestion

I feel that pets should be able to get XP from their kills.

**Comment by RobertSkalko** [comment]
Not too keen on pets honestly because last time i did nothing, the players complained the best farming meta was getting 30 wolves and letting them auto kill everything. So i probably won't be doing anything to make normal pets a thing.

Maybe if there was some spell that allowed you to select 1 of your pets as a primary pet or something, and made it work like summon..

**Comment by TerravoltPrime** [comment]
The summoning idea would be great

**Comment by TerravoltPrime** [comment]
also, they should gain xp on their own and xp should be non transferable to the owner

**Comment by RobertSkalko** [comment]
Not planned for now
