### ISSUE TITLE
[Suggestion] more HUD options

### ISSUE THREAD

**Issue by MrKashew** [RobertSkalko/Mine-And-Slash-Rework#3]
I'm sure this is likely already in the plans as it is in Beta
e.g. something like

Position of hud elements
- bottom right, top right, bottom left
- option to modify X and Y positions of individual bars
- drag and repositioning
- similar options for the 4 slots that appear on the left-middle screen

Scaling size of HUD text (such as Level up)

**Comment by RobertSkalko** [comment]
Added some overlay configs in latest update, but not for bars yet. Still unsure exactly on some specifics. I think  configs are ok but they look awful in the text file, there's just so many things in there because of the enum values.

Idk if i want each bar to be 1 config. That's 3 presets times 4 bars.. maybe if i could somehow not show the default configs in the config file but still allow a way to define custom presets

**Comment by RobertSkalko** [comment]
Done, though people claim it's too confusing so i'll see if  i can make the configs easier to use
