### ISSUE TITLE
Translation from English to Russian

### ISSUE THREAD

**Issue by Whitealbum0** [RobertSkalko/Mine-And-Slash-Rework#66]
[ru_ru.json](https://github.com/RobertSkalko/Mine-And-Slash-Rework/files/13980355/ru_ru.json)
You can add a translation, this translation is made with the help of a machine

**Comment by TUsama** [comment]
This mod welcomes translations/localizations from all over the world. However due to its term complexity and format sensitivity,   any translations/localizations need to ensure its term consistency and format correctness, otherwise the locale will literally be an obstacle to Russian players. 
I've roughly checked your translation, and found the problems below:

at "mmorpg.stat.armor_per_10_dodge": Dodge Rating -> очков уклонения
at ""mmorpg.stat.dodge" : Dodge Rating -> Рейтинг уклонения
Using different words to translate the same word "Rating ", and could be a misleading translation.

at "mmorpg.stat.chaining_spell_dmg": Chaining -> цепи
at "mmorpg.stat.plus_lvl_chaining_spells": Chaining -> цепляющим
Using different terms to  translate "Chaining". Considering the "Chaining" indicates the tag of this spell, you need to use the same word to avoid the potential misunderstanding.

Most MTs(Machine translation) are out of context, and barely can keep term consistency during the translation process unless you can provide a terms table.
